name: Deploy

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'client/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn build

      # - name: Run Test
      #   run: yarn test:remote
      - name: Deploy
        uses: sugatpoudel/git-deploy@v0.2
        with:
          changes: public
          repository: git@github.com:goonerholic/goonerholic.github.io.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}
          name: goonerholic
          email: goonerholic@gmail.com

        # run:
        #   git remote add gh-pages https://github.com/goonerholic/goonerholic.github.io.git
        #   git config --global user.name "goonerholic"
        #   git config --global user.email "goonerholic@gmail.com"
        #   yarn deploy
